HS8_BlogProject.UI/Areas/Admin/Controllers/AuthorController.cs
using HS8_BlogProject.Application.Models.DTOs.AuthorDTOs;
using HS8_BlogProject.Application.Models.VMs.AuthorVMs;
using HS8_BlogProject.Application.Models.VMs.PostVMs;
using HS8_BlogProject.UI.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Newtonsoft.Json;

namespace HS8_BlogProject.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AuthorController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var getData = ControllerRepository.ApiHttpGet<List<AuthorVM>>("Author/GetAuthors", Request.Cookies["X-Access-Token"]);

            if (getData.IsSuccessStatusCode)
            {
                string results = getData.Content.ReadAsStringAsync().Result;
                var model = JsonConvert.DeserializeObject<List<AuthorVM>>(results);

                return View(model);
            }
            return RedirectToAction("Login", "Account", new { area = "", returnUrl = Request.Path });
        }

        public async Task<IActionResult> Create()
        {
            var getData = ControllerRepository.ApiHttpGet<CreateAuthorDTO>("Author/CreateAuthor", Request.Cookies["X-Access-Token"]);

            if (getData.IsSuccessStatusCode)
            {
                string results = getData.Content.ReadAsStringAsync().Result;
                var model = JsonConvert.DeserializeObject<CreateAuthorDTO>(results);

                return View(model);
			}
			return RedirectToAction("Login", "Account", new { area = "", returnUrl = Request.Path });
		}

        [HttpPost]
        public async Task<IActionResult> Create(CreateAuthorDTO model)
        {
            if (ModelState.IsValid)
            {

                if (model.UploadPath != null)
                {
                    using var image = Image.Load(model.UploadPath.OpenReadStream());

                    // Resize
                    image.Mutate(x => x.Resize(600, 560));

                    Guid guid = Guid.NewGuid();
                    image.Save($"wwwroot/images/{guid}.jpg");

                    model.ImagePath = $"/images/{guid}.jpg";
                    model.UploadPath = null;
                }

                ControllerRepository.ApiHttpPost<CreateAuthorDTO>("Author/Create", model, Request.Cookies["X-Access-Token"]);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Create");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var getData = ControllerRepository.ApiHttpGet<UpdateAuthorDTO>("Author/GetById/" + id, Request.Cookies["X-Access-Token"]);

            if (getData.IsSuccessStatusCode)
            {
                string results = getData.Content.ReadAsStringAsync().Result;
                var model = JsonConvert.DeserializeObject<UpdateAuthorDTO>(results);

                return View(model);
			}
			return RedirectToAction("Login", "Account", new { area = "", returnUrl = Request.Path, id });
		}

        [HttpPost]
        public async Task<IActionResult> Edit(UpdateAuthorDTO model)
        {
            if (ModelState.IsValid)
            {

                if (model.UploadPath != null)
                {
                    using var image = Image.Load(model.UploadPath.OpenReadStream());

                    // Resize
                    image.Mutate(x => x.Resize(600, 560));

                    Guid guid = Guid.NewGuid();
                    image.Save($"wwwroot/images/{guid}.jpg");

                    model.ImagePath = $"/images/{guid}.jpg";
                    model.UploadPath = null;
                }

                ControllerRepository.ApiHttpPut<UpdateAuthorDTO>("Author/Update", model, Request.Cookies["X-Access-Token"]);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Edit");
        }

        public async Task<IActionResult> Delete(int id)
        {
            ControllerRepository.ApiHttpDelete("Author/Delete/" + id, Request.Cookies["X-Access-Token"]);

            return RedirectToAction("Index");
        }
    }
}

HS8_BlogProject.UI/Areas/Admin/Controllers/GenreController.cs
using HS8_BlogProject.Application.Models.DTOs.AuthorDTOs;
using HS8_BlogProject.Application.Models.DTOs.GenreDTOs;
using HS8_BlogProject.Application.Models.VMs.AuthorVMs;
using HS8_BlogProject.Application.Models.VMs.GenreVMs;
using HS8_BlogProject.UI.Controllers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Newtonsoft.Json;

namespace HS8_BlogProject.UI.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class GenreController : Controller
	{
		public async Task<IActionResult> Index()
		{
			var getData = ControllerRepository.ApiHttpGet<List<GenreVM>>("Genre/GetGenres", Request.Cookies["X-Access-Token"]);
            if (getData.IsSuccessStatusCode)
            {
                string results = getData.Content.ReadAsStringAsync().Result;
                var model = JsonConvert.DeserializeObject<List<GenreVM>>(results);

                return View(model);
			}
			return RedirectToAction("Login", "Account", new { area = "", returnUrl = Request.Path });
		}

		public async Task<IActionResult> Create()
		{
			if (Request.Cookies["username"] is not null)
			{
				return View(new CreateGenreDTO());
			}
			return RedirectToAction("Login", "Account", new { area = "", returnUrl = Request.Path });
		}

		[HttpPost]
		public async Task<IActionResult> Create(CreateGenreDTO model)
		{
			if (ModelState.IsValid)
			{
				ControllerRepository.ApiHttpPost<CreateGenreDTO>("Genre/Create", model, Request.Cookies["X-Access-Token"]);
				return RedirectToAction("Index");
            }
            return RedirectToAction("Create");
        }

		public async Task<IActionResult> Edit(int id)
		{
			var getData = ControllerRepository.ApiHttpGet<UpdateGenreDTO>("Genre/GetById/" + id, Request.Cookies["X-Access-Token"]);

            if (getData.IsSuccessStatusCode)
            {
                string results = getData.Content.ReadAsStringAsync().Result;
                var model = JsonConvert.DeserializeObject<UpdateGenreDTO>(results);

                return View(model);
			}
			return RedirectToAction("Login", "Account", new { area = "", returnUrl = Request.Path, id});
		}

		[HttpPost]
		public async Task<IActionResult> Edit(UpdateGenreDTO model)
		{
			if (ModelState.IsValid)
			{
				ControllerRepository.ApiHttpPut<UpdateGenreDTO>("Genre/Update", model, Request.Cookies["X-Access-Token"]);
				return RedirectToAction("Index");
            }
            return RedirectToAction("Edit");
        }

		public async Task<IActionResult> Delete(int id)
		{
			ControllerRepository.ApiHttpDelete("Genre/Delete/" + id, Request.Cookies["X-Access-Token"]);

			return RedirectToAction("Index");
		}
	}
}

HS8_BlogProject.UI/Areas/Admin/Controllers/LikeController.cs
using HS8_BlogProject.Application.Models.DTOs.AuthorDTOs;
using HS8_BlogProject.Application.Models.DTOs.CommentDTOs;
using HS8_BlogProject.Application.Models.DTOs.LikeDTOs;
using HS8_BlogProject.Application.Models.VMs.AuthorVMs;
using HS8_BlogProject.Application.Models.VMs.CommentVMs;
using HS8_BlogProject.Application.Models.VMs.LikeVMs;
using HS8_BlogProject.UI.Controllers;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace HS8_BlogProject.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class LikeController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var getData = ControllerRepository.ApiHttpGet<List<LikeVM>>("Like/GetLikes", Request.Cookies["X-Access-Token"]);

            if (getData.IsSuccessStatusCode)
            {
                string results = getData.Content.ReadAsStringAsync().Result;
                var model = JsonConvert.DeserializeObject<List<LikeVM>>(results);

                return View(model);
			}
			return RedirectToAction("Login", "Account", new { area = "", returnUrl = Request.Path });
		}

        public async Task<IActionResult> Create()
        {
            var getData = ControllerRepository.ApiHttpGet<CreateLikeDTO>("Like/CreateLike", Request.Cookies["X-Access-Token"]);

            if (getData.IsSuccessStatusCode)
            {
                string results = getData.Content.ReadAsStringAsync().Result;
                var model = JsonConvert.DeserializeObject<CreateLikeDTO>(results);

                return View(model);
			}
			return RedirectToAction("Login", "Account", new { area = "", returnUrl = Request.Path });
		}

        [HttpPost]
        public async Task<IActionResult> Create(CreateLikeDTO model)
        {
            if (ModelState.IsValid)
            {
                ControllerRepository.ApiHttpPost<CreateLikeDTO>("Like/Create", model, Request.Cookies["X-Access-Token"]);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Create");
        }

        public async Task<IActionResult> Delete(int id)
        {
            ControllerRepository.ApiHttpDelete("Like/Delete/" + id, Request.Cookies["X-Access-Token"]);

            return RedirectToAction("Index");
        }
    }
}

HS8_BlogProject.UI/Areas/Admin/Controllers/PostController.cs
using HS8_BlogProject.Application.Models.DTOs.AuthorDTOs;
using HS8_BlogProject.Application.Models.DTOs.PostDTOs;
using HS8_BlogProject.Application.Models.VMs.AuthorVMs;
using HS8_BlogProject.Application.Models.VMs.PostVMs;
using HS8_BlogProject.Domain.Entities;
using HS8_BlogProject.UI.Controllers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Newtonsoft.Json;

namespace HS8_BlogProject.UI.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class PostController : Controller
	{
		public async Task<IActionResult> Index()
        {
            var getData = ControllerRepository.ApiHttpGet<List<PostVM>>("Post/GetPosts", Request.Cookies["X-Access-Token"]);

            if (getData.IsSuccessStatusCode)
            {
                string results = getData.Content.ReadAsStringAsync().Result;
                var model = JsonConvert.DeserializeObject<List<PostVM>>(results);

                return View(model);
			}
			return RedirectToAction("Login", "Account", new { area = "", returnUrl = Request.Path });
		}

		public async Task<IActionResult> Create()
        {
            var getData = ControllerRepository.ApiHttpGet<CreatePostDTO>("Post/CreatePost", Request.Cookies["X-Access-Token"]);

            if (getData.IsSuccessStatusCode)
            {
                string results = getData.Content.ReadAsStringAsync().Result;
                var model = JsonConvert.DeserializeObject<CreatePostDTO>(results);

                return View(model);
			}
			return RedirectToAction("Login", "Account", new { area = "", returnUrl = Request.Path });
		}

		[HttpPost]
		public async Task<IActionResult> Create(CreatePostDTO model)
		{
			if (ModelState.IsValid)
            {

                if (model.UploadPath != null)
                {
                    using var image = Image.Load(model.UploadPath.OpenReadStream());

                    image.Mutate(x => x.Resize(600, 560));

                    Guid guid = Guid.NewGuid();
                    image.Save($"wwwroot/images/{guid}.jpg");

                    model.ImagePath = $"/images/{guid}.jpg";
                    model.UploadPath = null;
                }

                ControllerRepository.ApiHttpPost<CreatePostDTO>("Post/Create", model, Request.Cookies["X-Access-Token"]);
				return RedirectToAction("Index");
			}
			return RedirectToAction("Create");
		}

		public async Task<IActionResult> Edit(int id)
		{
            var getData = ControllerRepository.ApiHttpGet<UpdatePostDTO>("Post/GetById/" + id, Request.Cookies["X-Access-Token"]);

            if (getData.IsSuccessStatusCode)
            {
                string results = getData.Content.ReadAsStringAsync().Result;
                var model = JsonConvert.DeserializeObject<UpdatePostDTO>(results);

                return View(model);
			}
			return RedirectToAction("Login", "Account", new { area = "", returnUrl = Request.Path, id });
		}

		[HttpPost]
		public async Task<IActionResult> Edit(UpdatePostDTO model)
		{
			if (ModelState.IsValid)
            {

                if (model.UploadPath != null)
                {
                    using var image = Image.Load(model.UploadPath.OpenReadStream());

                    image.Mutate(x => x.Resize(600, 560));

                    Guid guid = Guid.NewGuid();
                    image.Save($"wwwroot/images/{guid}.jpg");

                    model.ImagePath = $"/images/{guid}.jpg";
                    model.UploadPath = null;
                }

                ControllerRepository.ApiHttpPut<UpdatePostDTO>("Post/Update", model, Request.Cookies["X-Access-Token"]);
				return RedirectToAction("Index");
			}
			return RedirectToAction("Edit");
		}

		public async Task<IActionResult> Details(int id)
		{
            var getData = ControllerRepository.ApiHttpGet<PostDetailsVM>("Post/GetPostDetails/" + id, Request.Cookies["X-Access-Token"]);

            if (getData.IsSuccessStatusCode)
            {
                string results = getData.Content.ReadAsStringAsync().Result;
                var model = JsonConvert.DeserializeObject<PostDetailsVM>(results);

                return View(model);
			}
			return RedirectToAction("Login", "Account", new { area = "", returnUrl = Request.Path, id });
		}

		public async Task<IActionResult> Delete(int id)
		{
			ControllerRepository.ApiHttpDelete("Post/Delete/" + id, Request.Cookies["X-Access-Token"]);

			return RedirectToAction("Index");
		}
	}
}

HS8_BlogProject.UI/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>@ViewData["Title"]</title>

	<!-- Google Font: Source Sans Pro -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="~/media/css/all.min.css">
	<!-- overlayScrollbars -->
	<link rel="stylesheet" href="~/media/css/OverlayScrollbars.min.css">
	<!-- Theme style -->
	<link rel="stylesheet" href="~/media/css/adminlte.min.css">
	@RenderSection("Css",required:false)
</head>
<body class="hold-transition sidebar-mini layout-fixed">
	<!-- Site wrapper -->
	<div class="wrapper">
		<!-- Navbar -->
		<nav class="main-header navbar navbar-expand navbar-white navbar-light">
			<!-- Left navbar links -->
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
				</li>
				<li class="nav-item d-none d-sm-inline-block">
					<a asp-controller="Dashboard" class="nav-link">Home</a>
				</li>
			</ul>

			<!-- Right navbar links -->
			<ul class="navbar-nav ml-auto">
				<!-- Navbar Search -->
				<li class="nav-item">
					<a class="nav-link" data-widget="navbar-search" href="#" role="button">
						<i class="fas fa-search"></i>
					</a>
					<div class="navbar-search-block">
						<form class="form-inline">
							<div class="input-group input-group-sm">
								<input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
								<div class="input-group-append">
									<button class="btn btn-navbar" type="submit">
										<i class="fas fa-search"></i>
									</button>
									<button class="btn btn-navbar" type="button" data-widget="navbar-search">
										<i class="fas fa-times"></i>
									</button>
								</div>
							</div>
						</form>
					</div>
				</li>
				<li class="nav-item">
					<a class="nav-link" asp-area="" asp-controller="" asp-action="">User Panel</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" asp-area="" asp-controller="Account" asp-action="ProfileDetails" asp-route-username="@Context.Request.Cookies["username"]">View Profile</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" asp-area="" asp-controller="Account" asp-action="Edit" asp-route-username="@Context.Request.Cookies["username"]">Edit Profile</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" asp-area="" asp-controller="Account" asp-action="LogOut">Log Out</a>
				</li>
			</ul>
		</nav>
		<!-- /.navbar -->
		<!-- Main Sidebar Container -->
		<aside class="main-sidebar sidebar-dark-primary elevation-4">
			<!-- Brand Logo -->
			<a asp-controller="Dashboard" class="brand-link">
				<img src="~/media/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
				<span class="brand-text font-weight-light">Admin Panel</span>
			</a>

			<!-- Sidebar -->
			<div class="sidebar">
				<!-- Sidebar user (optional) -->
				<div class="user-panel mt-3 pb-3 mb-3 d-flex">
					<a asp-area="" asp-controller="Account" asp-action="ProfileDetails" asp-route-username="@Context.Request.Cookies["username"]">
						<div class="image">
							<!-- ToDo: User Image Ekle-->
							<img src="~/images/defaultuser.jpg" class="img-circle elevation-2" alt="User Image">
							<span>@Context.Request.Cookies["username"]</span>
						</div>
					</a>
				</div>

				<!-- SidebarSearch Form -->
				<div class="form-inline">
					<div class="input-group" data-widget="sidebar-search">
						<input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
						<div class="input-group-append">
							<button class="btn btn-sidebar">
								<i class="fas fa-search fa-fw"></i>
							</button>
						</div>
					</div>
				</div>

				<!-- Sidebar Menu -->
				<nav class="mt-2">
					<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
						<!-- Add icons to the links using the .nav-icon class
							 with font-awesome or any other icon font library -->
						<li class="nav-item">
							<a asp-controller="Author" asp-action="" class="nav-link">
								<i class="nav-icon fas fa-tachometer-alt"></i>
								<p>
									Authors
								</p>
							</a>
						</li>
						<li class="nav-item">
							<a asp-controller="Comment" asp-action="" class="nav-link">
								<i class="nav-icon fas fa-tachometer-alt"></i>
								<p>
									Comments
								</p>
							</a>
						</li>
						<li class="nav-item">
							<a asp-controller="Genre" asp-action="" class="nav-link">
								<i class="nav-icon fas fa-tachometer-alt"></i>
								<p>
									Genres
								</p>
							</a>
						</li>
						<li class="nav-item">
							<a asp-controller="Like" asp-action="" class="nav-link">
								<i class="nav-icon fas fa-tachometer-alt"></i>
								<p>
									Likes
								</p>
							</a>
						</li>
						<li class="nav-item">
							<a asp-controller="Post" asp-action="" class="nav-link">
								<i class="nav-icon fas fa-tachometer-alt"></i>
								<p>
									Posts
								</p>
							</a>
						</li>
					</ul>
				</nav>
				<!-- /.sidebar-menu -->
			</div>
			<!-- /.sidebar -->
		</aside>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<section class="content-header"></section>

			<!-- Main content -->
			<section class="content">

				<div class="container-fluid">
					<div class="row">
						@RenderBody()
					</div>
				</div>
			</section>
			<!-- /.content -->
		</div>
		<!-- /.content-wrapper -->

		<footer class="main-footer">
			<div class="float-right d-none d-sm-block">
				<b>Version</b> 3.2.0
			</div>
			<strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
		</footer>

		<!-- Control Sidebar -->
		<aside class="control-sidebar control-sidebar-dark">
			<!-- Control sidebar content goes here -->
		</aside>
		<!-- /.control-sidebar -->
	</div>
	<!-- ./wrapper -->
	<!-- jQuery -->
	<script src="~/media/js/jquery.min.js"></script>
	<!-- Bootstrap 4 -->
	<script src="~/media/js/bootstrap.bundle.min.js"></script>
	<!-- overlayScrollbars -->
	<script src="~/media/js/jquery.overlayScrollbars.min.js"></script>
	<!-- AdminLTE App -->
	<script src="~/media/js/adminlte.min.js"></script>
	<!-- AdminLTE for demo purposes -->
	<script src="~/media/js/demo.js"></script>
	@RenderSection("Scripts",required:false)
</body>
</html>